document.writeln("<nav class=\"navbar navbar-default navbar-static-top\">");
document.writeln("	  <div class=\"container\">");
document.writeln("		<div class=\"navbar-header\" itemscope itemtype=\"http://schema.org/CreativeWork\">");
document.writeln("		  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">");
document.writeln("			<span class=\"sr-only\">Toggle navigation</span>");
document.writeln("			<span class=\"icon-bar\"></span>");
document.writeln("			<span class=\"icon-bar\"></span>");
document.writeln("			<span class=\"icon-bar\"></span>");
document.writeln("		  </button>");
document.writeln("		  <a itemprop=\"url\" class=\"navbar-brand bg_green\" href=\"http://fz.cmbc.com.cn\">");
document.writeln("			<img itemprop=\"image\" src=\"/wk_style/img/logo2.png\" alt=\"应届生求职网\" title=\"应届生求职网\" />");
document.writeln("		  </a>");
document.writeln("		</div>");
document.writeln("		<div id=\"navbar\" class=\"navbar-collapse collapse\">");
document.writeln("		  <ul class=\"nav navbar-nav\" itemscope itemtype=\"http://schema.org/WebPage\">                                  ");
document.writeln("			<li class=\"active\"><a itemprop=\"relatedLink\" href=\"/\">首页</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://bbs.yingjiesheng.com\">BBS</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://fz.cmbc.com.cn/commend-fulltime-1.html\">全职推荐</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://fz.cmbc.com.cn/commend-parttime-1.html\">实习推荐</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://s.yingjiesheng.com/\">职位搜索</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://my.fz.cmbc.com.cn/xuanjianghui.html\">宣讲会</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://zph.yingjiesheng.com/\">招聘会</a></li>");
document.writeln("			<li class=\"dropdown\">");
document.writeln("			  <a itemprop=\"relatedLink\" href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">更多 <span class=\"caret\"></span></a>");
document.writeln("			  <ul class=\"dropdown-menu\">");
document.writeln("				<li><a itemprop=\"relatedLink\" href=\"http://www.fz.cmbc.com.cn/industry/\">行业招聘</a></li>");
document.writeln("				<li><a itemprop=\"relatedLink\" href=\"http://s.yingjiesheng.com/result.jsp?keyword=%E5%85%AC%E5%8A%A1%E5%91%98+OR+%E4%BA%8B%E4%B8%9A%E5%8D%95%E4%BD%8D&do=2\">公务员</a></li>");
document.writeln("				<li><a itemprop=\"relatedLink\" href=\"http://www.fz.cmbc.com.cn/major/\">分类求职</a></li>");
document.writeln("				<li><a itemprop=\"relatedLink\" href=\"http://www.fz.cmbc.com.cn/deadline/\">网申截止</a></li>");
document.writeln("				<li><a itemprop=\"relatedLink\" href=\"http://vip.fz.cmbc.com.cn/newbook/\">求职书</a></li>");
document.writeln("			  </ul>");
document.writeln("			</li>");
document.writeln("		  </ul>");
document.writeln("		  <form class=\"navbar-form navbar-left\" role=\"search\" action=\"/so/\">");
document.writeln("			<div class=\"form-group\">");
document.writeln("			  <input type=\"text\" name=\"keyword\" class=\"form-control\" placeholder=\"Search\">");
document.writeln("			</div>");
document.writeln("			<button type=\"submit\" class=\"btn btn-default glyphicon glyphicon-search\"></button>");
document.writeln("		  </form>");
document.writeln("		  <ul class=\"nav navbar-nav navbar-right\">");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://k.yingjiesheng.com/\">登录</a></li>");
document.writeln("			<li><a itemprop=\"relatedLink\" href=\"http://my.fz.cmbc.com.cn/index.php/personal/register.htm\">注册</a></li>");
document.writeln("		  </ul>");
document.writeln("		</div><!--/.nav-collapse -->");
document.writeln("	  </div>");
document.writeln("	</nav>");